### ISSUE TITLE
adb push failed on Android 8.1 devices

### ISSUE THREAD

**Issue by tiann** [mobile-dev-inc/dadb#33]
```txt
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at okio.OutputStreamSink.write(JvmOkio.kt:56)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
	at dadb.AdbWriter.write(AdbWriter.kt:92)
	at dadb.AdbWriter.writeClose(AdbWriter.kt:60)
	at dadb.AdbStream.close(AdbStream.kt:118)
	at dadb.AdbStream.nextMessage(AdbStream.kt:109)
	at dadb.AdbStream.access$nextMessage(AdbStream.kt:24)
	at dadb.AdbStream$source$1.message(AdbStream.kt:61)
	at dadb.AdbStream$source$1.read(AdbStream.kt:40)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
	at dadb.AdbSyncStream.send(AdbSync.kt:73)
	at dadb.Dadb$DefaultImpls.push(Dadb.kt:54)
	at dadb.TestDadb.push(DadbTest.kt:331)
	at dadb.DadbTest$adbPush_basic$1.invoke(DadbTest.kt:119)
	at dadb.DadbTest$adbPush_basic$1.invoke(DadbTest.kt:113)
```

**Comment by tiann** [comment]
https://github.com/mobile-dev-inc/dadb/blob/master/dadb/src/main/kotlin/dadb/AdbSync.kt#L69

When the `DATA` is written, the read would fail with "Broken Pipe"

And i test Android 9, 10, 11, 12, it works well

**Comment by sharpordie** [comment]
I confirm this strange bug on Android 8.

@tiann
Do you have any solution to suggest for the dadb team?

**Comment by tiann** [comment]
I compared the difference of `system/core/adb/file_sync_service.cpp`  between Android 8.1 and Android 9.0, and the `do_recv` has some changes:

```diff
❯ diff file_sync_service_8.1.cpp file_sync_service_9.0.cpp
51,54c51,52
<     // TODO: use fs_config to configure permissions on /data.
<     return android::base::StartsWith(path, "/system/") ||
<            android::base::StartsWith(path, "/vendor/") ||
<            android::base::StartsWith(path, "/oem/");
---
>     // TODO: use fs_config to configure permissions on /data too.
>     return !android::base::StartsWith(path, "/data/");
65c63
<     cap_data.magic_etc = VFS_CAP_REVISION | VFS_CAP_FLAGS_EFFECTIVE;
---
>     cap_data.magic_etc = VFS_CAP_REVISION_2 | VFS_CAP_FLAGS_EFFECTIVE;
208a207,212
>
>     if (posix_fadvise(fd, 0, 0, POSIX_FADV_SEQUENTIAL | POSIX_FADV_NOREUSE | POSIX_FADV_WILLNEED) <
>         0) {
>         D("[ Failed to fadvise: %d ]", errno);
>     }
>
415a420,423
>     if (posix_fadvise(fd, 0, 0, POSIX_FADV_SEQUENTIAL | POSIX_FADV_NOREUSE) < 0) {
>         D("[ Failed to fadvise: %d ]", errno);
>     }
>
419c427
<         int r = adb_read(fd, &buffer[0], buffer.size());
---
>         int r = adb_read(fd, &buffer[0], buffer.size() - sizeof(msg.data));
```

I am not familiar with `dadb`'s file_sync, does this break something?

**Comment by tiann** [comment]
Here is the source code:

[file_sync_service.zip](https://github.com/mobile-dev-inc/dadb/files/9761032/file_sync_service.zip)

you can also read in online: http://aospxref.com/android-9.0.0_r61/xref/system/core/adb/file_sync_service.cpp
