### ISSUE TITLE
Install failed: cmd: Can't find service: package

### ISSUE THREAD

**Issue by carlonzo** [mobile-dev-inc/dadb#46]
Trying to run Maestro against an emulator with image `system-images;android-31;default;x86_64` but getting an exception while installing the Maestro apk.

here is the full exception:

```
Running on emulator-5554
java.io.IOException: Failed to install apk /tmp/maestro-app7402534504180399756.apk: Install failed: cmd: Can't find service: package
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:426)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:406)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:74)
	at maestro.Maestro$Companion.android(Maestro.kt:403)
	at maestro.Maestro$Companion.android$default(Maestro.kt:401)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:40)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:74)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:105)
Caused by: java.io.IOException: Install failed: cmd: Can't find service: package
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:85)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:424)
	... 15 more
cmd: Can't find service: package
cmd: Can't find service: package
```

Let me know if I can try anything for you to debug this?

**Comment by Leland-Takamine** [comment]
Hey @carlonzo looks like the emulator hasn't fully booted at the time you are running the Maestro Flow. `Can't find service: package` means that the package manager service has not initialized yet.
