### ISSUE TITLE
Dadb.list throws IOException on unauthorized device (OFFLINE)?

### ISSUE THREAD

**Issue by mrenouf** [mobile-dev-inc/dadb#55]
```
Exception in thread "main" java.io.IOException: Command failed (host:transport:13141FDD40019J): device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:137)
	at dadb.adbserver.AdbServerDadb.<init>(AdbServer.kt:128)
	at dadb.adbserver.AdbServer.createDadb(AdbServer.kt:52)
	at dadb.adbserver.AdbServer.listDadbs(AdbServer.kt:81)
	at dadb.adbserver.AdbServer.listDadbs$default(AdbServer.kt:60)
	at dadb.Dadb$Companion.list(Dadb.kt:244)
	at dadb.Dadb$Companion.list$default(Dadb.kt:243)
	at LogcatKt.list(Logcat.kt:36)
```

**Comment by flyfishxu** [comment]
When you first connect your target device, you need to authorize your phone. Usually, a dialog will show on your target device, you need to click "Allow", then you will have the permission to control your target device by adb.

**Comment by flyfishxu** [comment]
When you first connect your target device, you must authorize your phone. Usually, a dialog will show on your target device, you need to click "Allow", then you will have permission to control your target device by ADB.
