### ISSUE TITLE
SocketException: Broken pipe

### ISSUE THREAD

**Issue by leon-jakob-schneider** [mobile-dev-inc/dadb#56]
On the latest version I get this exception on push and install:

`Caused by: java.net.SocketException: Broken pipe

at okio.OutputStreamSink.write(JvmOkio.kt:56)

at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)

at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)

at okio.RealBufferedSink.writeIntLe(RealBufferedSink.kt:230)

at dadb.AdbWriter.write(AdbWriter.kt:78)

at dadb.AdbWriter.writeOpen(AdbWriter.kt:52)

at dadb.AdbConnection.open(AdbConnection.kt:47)

at dadb.DadbImpl.open(DadbImpl.kt:31)

at dadb.Dadb$DefaultImpls.openShell(Dadb.kt:43)

at dadb.DadbImpl.openShell(DadbImpl.kt:23)

at dadb.Dadb$DefaultImpls.shell(Dadb.kt:36)

at dadb.DadbImpl.shell(DadbImpl.kt:23)

`

 

On 1.2.3 file upload is working, but the installation is hanging endlessly. It seems like #41 solved the broken pipe issue, but a later commit reverted it.

 

I would really appreciate some help!

**Comment by LiJoeAllen** [comment]
https://github.com/mobile-dev-inc/dadb/pull/41

**Comment by LiJoeAllen** [comment]
@Leland-Takamine
