### ISSUE TITLE
What are the steps for connecting remotely?

### ISSUE THREAD

**Issue by mohammedavs** [mobile-dev-inc/dadb#72]
I have tried this but when I attempt to execute a shell command i get an error. 

What are the steps to connect without a usb cable?
Is it possible to connect remotely where the device is not connect to my wifi network?

`val device1 = Dadb.create("192.168.0.55", 5555)
`
Exception in thread "main" java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)

**Comment by sleekweasel** [comment]
If you can arrange to run your remote adb server with the -a flag, you can connect to that adb remotely, but you'll have to be careful about which device you use there:

```
remote$ adb -a nodaemon server
local$ adb -L tcp:remote:5037 devices
emulator-5554	device
local$ adb -L tcp:remote:5037 -s emulator-5554 shell echo hello world
```

This should correlate to

```
val dadb = AdbServer.createDadb(
        adbServerHost = "remote",
        adbServerPort = 5037,
        deviceQuery = "host:transport:emulator-5554"
    )
```
